# Site settings
baseurl = "http://ashirwad08.github.io/TheIntentionalMachine"
languageCode = "en-us"
title = "The Intentional Machine"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Ash Chakraborty"
	description = "Philosophy(StatisticalLearning(Data)); Philosophy(Data)"
	bio = "Data Science Apprentice - Philosopher - Advocate for a Space Faring Race"
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I Philosophize About Mind, Cognitive Science, and Epistemology, while pursuing Data Science applications preferably in the Space Exploration sector."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Nothing(Everything)"
	subtitle404 = "A glitch! Hit 'Back'."

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    dribble  = "https://www.dribbble.com/"
